language: java
jdk:
  - openjdk8

# Travis CI를 어느 브랜치가 푸쉬될 때 수행할 것인지?
branches:
  only:
    - spring/aws-spring-boot

# Travis CI 서버의 Home
# 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 해시하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# 설정한 브랜치에 푸쉬가 될 때 수행하는 명령어
script: "./gradlew clean build"

# deploy 명령어가 실행되기 전에 수행됩니다
# CodeDeploy 는 Jar 파일은 인식하지 못하므로 Jar+ 기타 설정 파일들을 모아 압축합니다.
# travis ci 는 s3 로 특정 파일만 업로드 할 순 없고 디렉토리 단위로만 업로드가 가능합니다
before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy 로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동 후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/aws-springboot.zip # deploy로 zip 파일 이동

# S3 로 파일 업로드 혹은 CodeDeploy 로 배포 등 외부 서비스와 연동될 행위들을 선언합니다.
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings environment variables
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings environment variables
    bucket: book-aws-springboot-build # s3 bucket
    region: ap-northeast-2
    skip_cleanup: true
    on:
      branch: spring/aws-spring-boot
    acl: private # zip 파일 접근을 private 으로 설정
    local_dir: deploy # before_deploy 에서 생성한 디렉토리, 해당 위치의 파일들만 S3 로 전송합니
    wait_until_deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings environment variables
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings environment variables
    bucket: book-aws-springboot-build # s3 bucket
    key: aws-springboot.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip # 압축 확장자
    application: aws-springboot # code deploy application in aws console
    deployment_group: aws-springboot-group # code deploy deployment groups in aws console
    region: ap-northeast-2
    wait_until_deployed: true
    on:
      branch: spring/aws-spring-boot

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - hjeong.you@gmail.com

