language: java
jdk:
  - openjdk8

# Travis CI를 어느 브랜치가 푸쉬될 때 수행할 것인지?
branches:
  only:
    - spring/aws-spring-boot

# Travis CI 서버의 Home
# 그레이들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 해시하여, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# 설정한 브랜치에 푸쉬가 될 때 수행하는 명령어
script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - hjeong.you@gmail.com