### Get all boards

GET http://localhost:3000/boards

### Create board

POST http://localhost:3000/boards
Content-Type: application/json

{
  "title": "t",
  "description": "d"
}

### Get board by ID

GET http://localhost:3000/boards/ddd

### Delete board by ID

DELETE http://localhost:3000/boards/ddd

### Update board's status

PATCH http://localhost:3000/boards/14927af0-9920-11ec-9ddc-6b4dda9c3cc0/status
Content-Type: application/json

{
  "status": "xxxxx"
}