server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/hyojeongyu/Desktop/study/backend-studies/msa-with-spring-cloud/git-local-repo
#          uri: https://github.com/hjyu94/backend-studies
#          username: xx
#          password: xx